name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm install hexo-cli -g
        
    - name: Install hexo-theme-butterfly
      run: |
        # 清理现有主题目录，避免冲突
        rm -rf themes/butterfly
        # 使用npm安装主题包
        npm install hexo-theme-butterfly
        # 创建主题目录链接
        mkdir -p themes
        ln -sf ../node_modules/hexo-theme-butterfly themes/butterfly || true
        
    - name: Build
      run: |
        echo "=== Environment Info ==="
        node --version
        npm --version
        echo "=== Checking dependencies ==="
        npm ls hexo
        npm ls hexo-theme-butterfly
        echo "=== Building site ==="
        hexo clean
        hexo generate --debug
        
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        hexo deploy