name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm install hexo-cli -g
        
    - name: Install hexo-theme-butterfly
      run: |
        npm install hexo-theme-butterfly
        
    - name: Build
      run: |
        hexo clean
        hexo generate
        
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        hexo deploy